name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: make
      run: make
    - name: make test-command
      run: make test-command
    - name: make test-parsing
      run: make test-parsing
    - name: make memtest
      run: make memtest
